CREATE TABLE roles (name VARCHAR(20) PRIMARY KEY);
INSERT INTO roles VALUES ('EMPLOYEE'), ('TECHNICIAN'), ('ADMIN');

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL CHECK (LENGTH(TRIM(name)) > 0),
    email VARCHAR(160) NOT NULL UNIQUE,
    password_hash VARCHAR(256) NOT NULL,
    role VARCHAR(20) NOT NULL REFERENCES roles(name),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(140) NOT NULL CHECK (LENGTH(TRIM(title)) > 0),
    description VARCHAR(6000) NOT NULL,
    category VARCHAR(20) NOT NULL CHECK (category IN ('Hardware','Software','Account','Network','Printer','Other')),
    priority VARCHAR(10) NOT NULL CHECK (priority IN ('Low','Medium','High','Critical')),
    status VARCHAR(20) NOT NULL DEFAULT 'Open' CHECK (status IN ('Open','Assigned','In Progress','Waiting','Resolved','Closed')),
    creator_id BIGINT NOT NULL REFERENCES users(id),
    assignee_id BIGINT REFERENCES users(id),
    resolution VARCHAR(3000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    version INTEGER NOT NULL DEFAULT 0,
    CHECK (status NOT IN ('Assigned','In Progress','Waiting','Resolved','Closed') OR assignee_id IS NOT NULL),
    CHECK (status NOT IN ('Resolved','Closed') OR (resolved_at IS NOT NULL AND LENGTH(TRIM(resolution)) > 0))
);
CREATE INDEX idx_ticket_creator ON tickets(creator_id);
CREATE INDEX idx_ticket_queue ON tickets(status, priority, assignee_id);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES tickets(id),
    author_id BIGINT NOT NULL REFERENCES users(id),
    body VARCHAR(3000) NOT NULL CHECK (LENGTH(TRIM(body)) > 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE ticket_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES tickets(id),
    actor_id BIGINT NOT NULL REFERENCES users(id),
    event VARCHAR(400) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_history_ticket ON ticket_history(ticket_id, id);

CREATE TABLE assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL CHECK (type IN ('Laptop','Desktop','Monitor','Phone','Tablet','Keyboard','Mouse','Other')),
    manufacturer VARCHAR(80) NOT NULL,
    model VARCHAR(100) NOT NULL,
    serial_number VARCHAR(100) NOT NULL UNIQUE,
    purchase_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'Available' CHECK (status IN ('Available','Assigned','Repair','Retired')),
    version INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE asset_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id BIGINT NOT NULL REFERENCES assets(id),
    user_id BIGINT NOT NULL REFERENCES users(id),
    assigned_by BIGINT NOT NULL REFERENCES users(id),
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    returned_at TIMESTAMP,
    active_asset_id BIGINT GENERATED ALWAYS AS (CASE WHEN returned_at IS NULL THEN asset_id ELSE NULL END),
    CONSTRAINT one_current_owner UNIQUE(active_asset_id)
);
